server:
  port: 7001  #该 Module 的端口号

eureka:
  instance:
    hostname: eureka7001 #eureka服务端的实例名称，

  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机版服务注册中心
      defaultZone: http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/ #一组互相注册的 Eureka Server 集群

#  server:
#    #false 关闭 Eureka 的自我保护机制，默认是开启。一般不建议大家修改 Eureka Server 在一段时间内（默认为 90 秒）没有接收到某个服务提供者（Eureka Client）的心跳，就会将这个服务提供者提供的服务从服务注册表中移除
#    enable-self-preservation: false
